project_id = "mtjqlqyasgleiwnmnfvd"

[functions.shopify-storefront]
verify_jwt = false

[functions.remove-background]
verify_jwt = false

[functions.mailchimp-subscribe]
verify_jwt = false

[functions.na-expert-chat]
verify_jwt = false

[functions.wholesale-chat]
verify_jwt = false

[functions.generate-recipes]
verify_jwt = false

[functions.sync-wholesale-shopify]
verify_jwt = false

[functions.scrape-blog]
verify_jwt = false

[functions.download-blog-image]
verify_jwt = false
